version: '3'
services:
    middle_mongo:
        image: mongo:latest
        env_file:
            - ./middle_example/.env
        ports:
            - 27017:27017
        volumes:
            - ./middle_example/mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
            - ./data/db:/data/db

    rest-api:   
        depends_on:
            - middle_mongo
        links:
            - middle_mongo
        build: ./middle_example
        ports:
            - 3000:3000
        restart: on-failure
        #environment:
        #    - WEB_HOST=web-app
        #    - WEB_PORT=5000
